import { Allerta_Stencil} from "next/font/google";
import "./globals.css";
import NavBar from "./component/header/NavBar";


const allertaStencil = Allerta_Stencil({
  weight: "400", // الخط ده عنده وزن واحد بس
  subsets: ["latin"], 
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${allertaStencil.variable}  antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
